name: Github Actions Demo
on: [push]
jobs:
  job_run_python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - run: python3 hiya.py
    
  job_create_directory:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - run: mkdir new_directory
    
  job_add_new_line:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - run: echo "print ('Hello Mars')" >> hiya.py
    - run: python3 hiya.py
